import { useState } from 'react';
import { motion } from 'framer-motion';
import CountUp from './CountUp';
import { exportSummary } from '../services/api';

function CompletionScreen({ sessionData, chunksText, onNewSession }) {
  const [isExporting, setIsExporting] = useState(false);
  const handleDownloadReport = async () => {
    setIsExporting(true);
    try {
      // 1. Try to get AI Summary
      let summaryText = '';
      if (chunksText) {
        const result = await exportSummary(chunksText);
        if (result.success) {
          summaryText = result.data.text + '\n\n';
        }
      }

      const reportContent = `
FocusRoom Session Report
========================
Date: ${new Date().toLocaleDateString()}
Time Focused: ${sessionData.timeElapsed || 0} minutes
Chunks Mastered: ${sessionData.chunksCompleted || 0}
${sessionData.quizStats && !sessionData.quizStats.skipped ? `Quiz Score: ${sessionData.quizStats.score || 0} / ${sessionData.quizStats.total || 0}\n` : ''}

${summaryText}
Generated by FocusRoom - Your Advanced Learning Platform
      `.trim();

      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `FocusSession_Summary_${new Date().toISOString().split('T')[0]}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to export summary", err);
      alert("Failed to export summary. Please try again.");
    } finally {
      setIsExporting(false);
    }
  };

  const handleShare = async () => {
    const shareText = `I just hyper-focused for ${sessionData.timeElapsed || 0} minutes and mastered ${sessionData.chunksCompleted || 0} chunks of complex material on FocusRoom! 🧠⚡`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'FocusRoom Session',
          text: shareText,
        });
      } catch (err) {
        console.log('Share canceled', err);
      }
    } else {
      navigator.clipboard.writeText(shareText);
      alert('Share text copied to clipboard!');
    }
  };

  return (
    <div className="completion-screen" style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 'var(--space-2xl) 0' }}>
      <motion.div 
        className="completion-content glass-card"
        initial={{ opacity: 0, y: 50 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, type: 'spring' }}
        style={{ textAlign: 'center', maxWidth: '600px', width: '90%', padding: 'var(--space-2xl)' }}
      >
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1, rotate: 360 }}
          transition={{ duration: 0.8, delay: 0.2, type: 'spring' }}
          style={{ fontSize: '5rem', marginBottom: 'var(--space-md)' }}
        >
          🏆
        </motion.div>
        
        <h1 style={{ background: 'var(--gradient-main)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', marginBottom: 'var(--space-xl)' }}>Session Complete!</h1>
        
        <div className="completion-stats" style={{ display: 'grid', gridTemplateColumns: sessionData.quizStats && !sessionData.quizStats.skipped ? '1fr 1fr 1fr' : '1fr 1fr', gap: 'var(--space-lg)', marginBottom: 'var(--space-2xl)' }}>
          <motion.div 
            className="stat-card glass-card"
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4 }}
            style={{ padding: 'var(--space-xl) var(--space-md)' }}
          >
            <div style={{ fontSize: '3.5rem', fontWeight: '800', color: 'var(--accent-cyan)', lineHeight: '1' }}>
              <CountUp end={sessionData.chunksCompleted || 0} />
            </div>
            <div style={{ color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px', marginTop: 'var(--space-sm)', fontSize: '0.9rem', fontWeight: '600' }}>Chunks Mastered</div>
          </motion.div>
          
          <motion.div 
            className="stat-card glass-card"
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.6 }}
            style={{ padding: 'var(--space-xl) var(--space-md)' }}
          >
            <div style={{ fontSize: '3.5rem', fontWeight: '800', color: 'var(--accent-purple)', lineHeight: '1' }}>
              <CountUp end={sessionData.timeElapsed || 0} />
            </div>
            <div style={{ color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px', marginTop: 'var(--space-sm)', fontSize: '0.9rem', fontWeight: '600' }}>Minutes Focused</div>
          </motion.div>

          {sessionData.quizStats && !sessionData.quizStats.skipped && (
            <motion.div 
              className="stat-card glass-card"
              initial={{ opacity: 0, x: 50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.8 }}
              style={{ padding: 'var(--space-xl) var(--space-md)' }}
            >
              <div style={{ fontSize: '3.5rem', fontWeight: '800', color: 'var(--accent-pink)', lineHeight: '1' }}>
                <CountUp end={sessionData.quizStats.score || 0} />/<CountUp end={sessionData.quizStats.total || 0} />
              </div>
              <div style={{ color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px', marginTop: 'var(--space-sm)', fontSize: '0.9rem', fontWeight: '600' }}>Quiz Score</div>
            </motion.div>
          )}
        </div>

        <motion.p 
          className="completion-message"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8 }}
          style={{ fontSize: '1.2rem', color: 'var(--text-secondary)', marginBottom: 'var(--space-2xl)', lineHeight: '1.6' }}
        >
          Great work! You conquered distractions and completed your session. 
          Your brain is building serious study muscles! 💪
        </motion.p>

        <motion.div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <motion.button 
            className="btn btn-primary btn-lg" 
            onClick={onNewSession}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.0 }}
            style={{ width: '100%', borderRadius: 'var(--radius-xl)' }}
          >
            Start New Session <span>🚀</span>
          </motion.button>

          <motion.div style={{ display: 'flex', gap: '1rem', width: '100%' }}>
            <motion.button 
              className="btn btn-secondary btn-lg" 
              onClick={handleDownloadReport}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1.1 }}
              style={{ flex: 1, borderRadius: 'var(--radius-xl)' }}
              disabled={isExporting}
            >
              {isExporting ? 'Generating...' : 'Export AI Summary 📝'}
            </motion.button>

            <motion.button 
              className="btn btn-secondary btn-lg" 
              onClick={handleShare}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1.2 }}
              style={{ flex: 1, borderRadius: 'var(--radius-xl)' }}
            >
              Share Progress 🏆
            </motion.button>
          </motion.div>
        </motion.div>
      </motion.div>
    </div>
  );
}

export default CompletionScreen;
